add_rules("mode.debug", "mode.release")
set_languages("c++20")
add_requires("gtest")

target("infinite_lib")
    set_basename("infinite")
    set_kind("shared")
    add_files("lib/*.cc")
    add_includedirs("include", { public = true })
    add_cxxflags("-Werror")

target("infinite_qwen3")
    set_kind("shared")
    add_files("arch/qwen3/*.cc")
    add_includedirs("include", { public = true })
    add_includedirs("lib")
    add_deps("infinite_lib")
    add_cxxflags("-Werror")

target("infinite_bin")
    set_basename("infinite")
    set_kind("binary")
    add_files("bin/*.cc")
    add_includedirs("include", { public = true })
    add_deps("infinite_lib")
    add_deps("infinite_qwen3")
    add_cxxflags("-Werror")

target("test")
    set_kind("binary")
    add_files("test/*.cc", "bin/*.cc")
    remove_files("bin/main.cc")
    add_includedirs("include", { public = true })
    add_includedirs("lib", "bin", "arch/qwen3")
    add_deps("infinite_lib")
    add_deps("infinite_qwen3")
    add_packages("gtest")
    add_links("gtest_main")
    add_tests("default")
    set_rundir(os.projectdir() .. "/test")
    add_cxxflags("-Werror")
