add_rules("mode.debug", "mode.release")

target("infinite")
    set_kind("shared")
    add_files("lib/*.cc")
    add_includedirs("include", { public = true })
    add_cxxflags("-std=c++20")

target("infinite_qwen3")
    set_kind("shared")
    add_files("arch/qwen3/*.cc")
    add_includedirs("include", { public = true })
    add_includedirs("lib")
    add_cxxflags("-std=c++20")
    add_deps("infinite")

target("infinite_bin")
    set_basename("infinite")
    set_kind("binary")
    add_files("bin/*.cc")
    add_includedirs("include", { public = true })
    add_cxxflags("-std=c++20")
    add_deps("infinite")
    add_deps("infinite_qwen3")
